const styles = {
    wrapper: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
        height: '100%',
    },
    form: {
        background: '#fff',
        padding: '30px',
        borderRadius: '10px',
        boxShadow: '0 4px 10px rgba(0, 0, 0, 0.1)',
        width: '100%',
        maxWidth: '400px',
        textAlign: 'center',
    },
    heading: {
        fontSize: '24px',
        marginBottom: '20px',
        color: '#333',
    },
    inputGroup: {
        marginBottom: '20px',
    },
    inputField: {
        width: '100%',
        padding: '12px 15px',
        fontSize: '16px',
        borderRadius: '8px',
        border: '1px solid #ddd',
        boxShadow: 'inset 0 1px 3px rgba(0, 0, 0, 0.1)',
        marginTop: '5px',
        transition: 'border-color 0.3s',
    },
    submitBtn: {
        width: '100%',
        padding: '12px',
        backgroundColor: '#007BFF',
        color: 'white',
        border: 'none',
        borderRadius: '8px',
        fontSize: '16px',
        cursor: 'pointer',
        transition: 'background-color 0.3s',
    },
    homeBtn: {
        width: '100%',
        padding: '12px',
        backgroundColor: '#6c757d',
        color: 'white',
        border: 'none',
        borderRadius: '8px',
        fontSize: '16px',
        cursor: 'pointer',
        marginTop: '10px',
    },
    logoutBtn: {
        width: '100%',
        padding: '12px',
        backgroundColor: '#dc3545',
        color: 'white',
        border: 'none',
        borderRadius: '8px',
        fontSize: '16px',
        cursor: 'pointer',
        marginTop: '20px',
    },
    errorMessage: {
        color: 'red',
        fontSize: '14px',
        marginTop: '10px',
        padding: '5px',
    },
};

export default styles;
